# Generated by Django 3.0.1 on 2020-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200102_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='ratings',
            field=models.ManyToManyField(to='core.Rating'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
