# Generated by Django 3.0.1 on 2020-01-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200102_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='ranking',
        ),
    ]
